name = "odds-and-endpoints-api"
compatibility_date = "2025-04-24"
main = "./.output/server/index.mjs"
compatibility_flags = [ "nodejs_compat" ]
assets = { directory = "./.output/public/", binding = "ASSETS" }
